http:
  routers:
    owntrack:
      rule: PathPrefix(`/owntrack`)
      service: owntrack
      middlewares:
        - owntrack-headers
        - owntrack-auth
  services:
    owntrack:
      loadbalancer:
        servers:
          - url: http://owntrack-trmnl:80
  middlewares:
    owntrack-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
    owntrack-auth:
      basicAuth:
        headerField: X-AuthenticatedUser
        users:
          # Generate using `htpasswd -nB <username>`
          - "example1:encoded_pass1"
