tls:
  certificates:
    - certFile: "/config/TS_HOST.TS_DOMAIN.ts.net.crt"
      keyFile: "/config/TS_HOST.TS_DOMAIN.ts.net.key"
  options:
    default:
      sniStrict: true
http:
  serversTransports:
    ignorecert:
      insecureSkipVerify: true
  routers:
    owntrack:
      rule: PathPrefix(`/owntrack`)
      service: owntrack
      tls: true
      middlewares:
        - owntrack-headers
        - owntrack-auth
  services:
    owntrack:
      loadbalancer:
        servers:
          - url: http://owntrack-trmnl:80
  middlewares:
    owntrack-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
          X-Forwarded-Host: TS_HOST.TS_DOMAIN.ts.net
    owntrack-auth:
      basicAuth:
        headerField: X-AuthenticatedUser
        users:
          # Generate using `htpasswd -nB <username>`
          - "example1:encoded_pass1"
